spring:
  application:
    name: management
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gfg_practice
    username: root
    password: blackhat

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9000
  servlet:
    context-path: /api

jwt:
  secret: this-is-a-very-long-secret-string-jdaflsdjflsdkjf32324
  expiry: 900