spring:
  application:
    name: oauth-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth-demo
    username: root
    password: blackhat

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GH_CLIENT_ID}
            client-secret: ${GH_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

server:
  port: 9000

jwt:
  secret: this-is-a-very-long-secret-string-jdaflsdjflsdkjf32324
  expiry: 900